app/app/feed/forms.py
from wtforms import Form, StringField, validators


class FeedPostForm(Form):
    message = StringField(validators=[validators.required()])

app/app/follower/forms.py
from wtforms import Form, StringField


class FilterForm(Form):
    last_name_like = StringField('Last Name', render_kw={'placeholder': None})
    name_like = StringField('Name', render_kw={'placeholder': None})

app/app/chat/views.py
from flask import Blueprint, render_template, abort
from flask_login import login_required, current_user
from injector import inject

from app.consul.services import ServiceDiscovery
from app.db.repositories import UserFollowerRepository

chat = Blueprint('chat', __name__, url_prefix='/chat')


@inject
@chat.route('/', methods=['GET'])
@login_required
def index(user_follower_repository: UserFollowerRepository, service_discovery: ServiceDiscovery):
    followers = user_follower_repository.find_all(
        current_user_id=current_user.id,
        accepted=True
    )

    return render_template(
        'chat-list.html',
        follower_list=[v.get_info(current_user.id) for k, v in followers.items()],
        chat_app_url=service_discovery.get('chat-app').address
    )


@inject
@chat.route('/<user_id>', methods=['GET'])
@login_required
def message_list(user_id, repository: UserFollowerRepository, service_discovery: ServiceDiscovery):
    user = repository.find_one(
        current_user_id=current_user.id,
        user_id=user_id,
        accepted=True
    )
    if not user:
        abort(404)

    return render_template(
        'chat-message-list.html',
        user_id=user.id,
        follower=user.get_info(current_user.id),
        chat_app_url=service_discovery.get('chat-app').address
    )

app/app/feed/__init__.py
from app.feed import events

app/app/feed/views.py
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user
from injector import inject

from app.feed.forms import FeedPostForm
from app.feed.services import FeedService

feed = Blueprint('feed', __name__, url_prefix='/feed')


@inject
@feed.route('/', defaults={'page': 1}, methods=['GET'])
@feed.route('/<page>', methods=['GET'])
@login_required
def index(page, service: FeedService):
    feed_posts, pagination_params = service.fetch_feed(current_user.id, int(page))

    if request.args.get('json'):
        return {
            'list': feed_posts,
            'pagination': pagination_params,
        }

    return render_template(
        'feed.html',
        list=feed_posts,
        pagination=pagination_params if feed_posts else None,
    )


@inject
@feed.route('/post/add', methods=['POST'])
@login_required
def add_post(service: FeedService):
    form = FeedPostForm(data=request.get_json())
    if not form.validate():
        return {'success': False, 'errors': form.errors}
    post = service.add_post(current_user.id, form.message.data)

    return {'success': True, 'message': post.as_dict(True)}

app/app/follower/views.py
from flask import Blueprint, abort, render_template, request
from flask_login import login_required, current_user
from injector import inject

from app.db.repositories import UserRepository, UserFollowerRepository, UserTarantoolRepository
from app.follower.exceptions import FollowerAlreadyExistsException, FollowerDoesNotExistsException
from app.follower.forms import FilterForm
from app.follower.services import FollowerService

follower = Blueprint('follower', __name__, url_prefix='/follower')


@inject
@follower.route('/<user_id>', methods=['GET'])
@login_required
def index(user_id, repository: UserFollowerRepository):
    user = repository.find_one(
        current_user_id=current_user.id,
        user_id=int(user_id)
    )
    if not user:
        abort(404)

    users = repository.find_all(
        current_user_id=user.id,
        accepted=True
    )
    return render_template(
        'follower.html',
        item=user.get_info(current_user.id),
        followers=[v.get_info(user_id) for k, v in users.items()],
    )


@inject
@follower.route('/list', defaults={'page': 1}, methods=['GET'])
@follower.route('/list/<page>', methods=['GET'])
@login_required
def list_accepted(page, repository: UserFollowerRepository):
    pagination = repository.paginate_all(
        current_user_id=current_user.id,
        accepted=True,
        limit=10,
        page=int(page)
    )
    return render_template(
        'follower-list.html',
        title='Followers',
        list=[v.get_info(current_user.id) for k, v in pagination.list.items()],
        pagination=pagination.get_params(),
    )


@inject
@follower.route('/list/all', defaults={'page': 1}, methods=['GET'])
@follower.route('/list/all/<page>', methods=['GET'])
@login_required
def list_all(page, repository: UserFollowerRepository):
    filter_form = FilterForm(data=request.args.to_dict())
    pagination = repository.paginate_all(
        current_user_id=current_user.id,
        last_name_like=filter_form.last_name_like.data,
        name_like=filter_form.name_like.data,
        limit=10,
        page=int(page)
    )
    return render_template(
        'follower-list.html',
        title='Profiles',
        list=[v.get_info(current_user.id) for k, v in pagination.list.items()],
        pagination=pagination.get_params(),
        form=filter_form,
    )


@inject
@follower.route('/list/all/tarantool', defaults={'page': 1}, methods=['GET'])
@follower.route('/list/all/tarantool/<page>', methods=['GET'])
@login_required
def list_all_tarantool(page, repository: UserTarantoolRepository):
    filter_form = FilterForm(data=request.args.to_dict())
    pagination = repository.paginate_all(
        last_name_like=filter_form.last_name_like.data,
        name_like=filter_form.name_like.data,
        limit=10,
        page=int(page)
    )

    return render_template(
        'follower-list.html',
        title='Profiles',
        list=[v.get_info(current_user.id) for k, v in pagination.list.items()],
        pagination=pagination.get_params(),
        form=filter_form,
        show_actions=False,
    )


@inject
@follower.route('/send/<user_id>', methods=['POST'])
@login_required
def send(user_id, repository: UserRepository, service: FollowerService):
    user = repository.find_one(id=user_id)
    if not user:
        abort(404)
    try:
        service.send(current_user, user)
    except FollowerAlreadyExistsException as e:
        return {'success': False, 'errors': [(str(e))]}
    return {'success': True, 'errors': []}


@inject
@follower.route('/accept/<user_id>', methods=['POST'])
@login_required
def accept(user_id, repository: UserRepository, service: FollowerService):
    user = repository.find_one(id=user_id)
    if not user:
        abort(404)
    try:
        service.accept(current_user, user)
    except FollowerDoesNotExistsException as e:
        return {'success': False, 'errors': [(str(e))]}
    return {'success': True, 'errors': []}

app/app/main/views.py
from flask import Blueprint, redirect, url_for
from flask_login import login_required, current_user

main = Blueprint('main', __name__, url_prefix='/')


@main.route('/')
@login_required
def index():
    return redirect(url_for('follower.index', user_id=current_user.get_id()))

app/app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Social Network</title>
</head>
<body>
<div id="app">
    <b-navbar
            toggleable="lg"
            class="border-bottom box-shadow mb-4"
            :sticky="true"
            style="background-color: rgb(244,244,244)"
    >
        <b-avatar
                class="mr-2"
                button
                rounded
                :size="36"
                @click="location.href = '{{ url_for('feed.index') }}'"
        ><b>SN</b></b-avatar>
        <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>
        <b-collapse id="nav-collapse" is-nav>
            <b-navbar-nav>
                <b-nav-item href="{{ url_for('feed.index') }}">Feed</b-nav-item>
                <b-nav-item href="{{ url_for('follower.list_all') }}">Profiles</b-nav-item>
                <b-nav-item href="{{ url_for('follower.list_accepted') }}">Followers</b-nav-item>
                <b-nav-item href="{{ url_for('chat.index') }}">Chats</b-nav-item>
            </b-navbar-nav>
            <b-navbar-nav class="ml-auto">
                {% if current_user.get_id() %}
                    <b-nav-item-dropdown right>
                        <template v-slot:button-content>
                            <b-avatar :size="24"></b-avatar>
                        </template>
                        <b-dropdown-item href="{{ url_for('main.index') }}">Profile</b-dropdown-item>
                        <b-dropdown-item href="{{ url_for('auth.logout') }}">Sign Out</b-dropdown-item>
                    </b-nav-item-dropdown>
                {% endif %}
            </b-navbar-nav>
        </b-collapse>
    </b-navbar>
    <div id="content">{% block content %}{% endblock %}</div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
    </footer>
</div>
<script src="{{ url_for('static', filename='build/bundle.js') }}"></script>
</body>
</html>

app/app/templates/chat-list.html
{% extends "base.html" %}
{% block content %}
<b-container>
    <h3>Chats</h3>
    <hr>
    <v-chat-list
            :follower-list="{{ follower_list|tojson_escaped }}"
            chat-message-list-url="{{ url_for('chat.message_list', user_id=':id') }}"
            chat-app-url="{{ chat_app_url }}"
    ></v-chat-list>
</b-container>
{% endblock %}

app/app/templates/chat-message-list.html
{% extends "base.html" %}
{% block content %}
<b-container>
    <h3>Chat with: {{ follower.last_name }} {{ follower.name }}</h3>
    <hr>
    <v-chat-message-list
            :user-id="{{ user_id }}"
            follower-url="{{ url_for('follower.index', user_id=':id') }}"
            chat-app-url="{{ chat_app_url }}"
    ></v-chat-message-list>
</b-container>
{% endblock %}

app/app/templates/feed.html
{% extends "base.html" %}
{% block content %}
<b-container>
    <h3>Feed</h3>
    <hr>
    <v-feed
        {% if current_user.is_authenticated %}
            user-id="{{ current_user.get_id() }}"
        {% endif %}
        :list="{{ list|tojson_escaped }}"
        feed-url="{{ url_for('feed.index', page=':page') }}"
        add-post-url="{{ url_for('feed.add_post') }}"
        {% if pagination %}
            :pagination="{{ pagination }}"
        {% endif %}
    ></v-feed>
</b-container>
{% endblock %}

app/app/templates/follower-list.html
{% extends "base.html" %}
{% block content %}
<b-container>
    <h3>{{ title }}</h3>
    <hr>
    {% if form %}
        <v-filter-form
                url="{{ request.path }}"
                :form="{{ form|form_tojson }}"
                submit-button-title="Find"
        ></v-filter-form>
        <hr>
    {% endif %}
    <v-follower-list
            :list="{{ list|tojson_escaped }}"
            follower-url="{{ url_for('follower.index', user_id=':id') }}"
            {% if request.query_string %}
                followers-url="{{ url_for(request.endpoint, page=':page') }}?{{ request.query_string.decode('utf-8') }}"
            {% else %}
                followers-url="{{ url_for(request.endpoint, page=':page') }}"
            {% endif %}

            send-url="{{ url_for('follower.send', user_id=':id') }}"
            accept-url="{{ url_for('follower.accept', user_id=':id') }}"
            {% if pagination %}
                :pagination="{{ pagination }}"
            {% endif %}
            {% if show_actions == False %}
                :show-actions="false"
            {% endif %}
    ></v-follower-list>
</b-container>
{% endblock %}

app/app/templates/follower.html
{% extends "base.html" %}
{% block content %}
<b-container>
    <h3>{{ item.last_name }} {{ item.name }}</h3>
    <hr>
    <v-follower
            :item="{{ item|tojson_escaped }}"
            :followers="{{ followers|tojson_escaped }}"
            follower-url="{{ url_for('follower.index', user_id=':id') }}"
            send-url="{{ url_for('follower.send', user_id=':id') }}"
            accept-url="{{ url_for('follower.accept', user_id=':id') }}"
    ></v-follower>
</b-container>
{% endblock %}

app/app/templates/login.html
{% extends "base.html" %}
{% block content %}
    <b-container class="w-50">
        <h1 class="text-center">Login</h1>
        <hr>
        <b-alert show variant="info">Don't have an account yet?
            <b-link to="{{ url_for('auth.register') }}">Register</b-link>
        </b-alert>
        <v-form
                url="{{ url_for('auth.login_form') }}"
                :form="{{ form|form_tojson }}"
                submit-button-title="Login"
                @success="location.href = '{{ url_for('main.index') }}'"
        ></v-form>
    </b-container>
{% endblock %}

app/app/templates/register.html
{% extends "base.html" %}
{% block content %}
    <b-container class="w-50">
        <h1 class="text-center">Registration</h1>
        <hr>
        <b-alert show variant="info">Already have an account?
            <b-link to="{{ url_for('auth.login') }}">Login</b-link>
        </b-alert>
        <v-form
                url="{{ url_for('auth.register') }}"
                :form="{{ form|form_tojson }}"
                submit-button-title="Register"
                @success="location.href = '{{ url_for('auth.login') }}'"
        ></v-form>
    </b-container>
{% endblock %}